// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var card = Emotion.css(undefined, /* :: */[
      Emotion.label("card"),
      /* :: */[
        Emotion.width(/* `pct */[
              5591841,
              33.0
            ]),
        /* :: */[
          Emotion.overflow(/* hidden */-862584982),
          /* :: */[
            Emotion.display(/* flex */-1010954439),
            /* :: */[
              Emotion.flexDirection(/* column */-963948842),
              /* :: */[
                Emotion.alignItems(/* center */98248149),
                /* :: */[
                  Emotion.boxShadows(/* :: */[
                        /* tuple */[
                          /* `px */[
                            25096,
                            0
                          ],
                          /* `px */[
                            25096,
                            2
                          ],
                          /* `px */[
                            25096,
                            4
                          ],
                          /* `px */[
                            25096,
                            0
                          ],
                          /* `rgba */[
                            -878128972,
                            /* tuple */[
                              0,
                              0,
                              0,
                              0.2
                            ]
                          ],
                          false
                        ],
                        /* [] */0
                      ]),
                  /* :: */[
                    Emotion.margin(/* `em */[
                          22632,
                          1.0
                        ]),
                    /* :: */[
                      Emotion.padding(/* `em */[
                            22632,
                            1.0
                          ]),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var img = Emotion.css(undefined, /* :: */[
      Emotion.label("img"),
      /* :: */[
        Emotion.width(/* `pct */[
              5591841,
              100.0
            ]),
        /* :: */[
          Emotion.height(/* `em */[
                22632,
                6.0
              ]),
          /* :: */[
            Emotion.marginBottom(/* `em */[
                  22632,
                  1.0
                ]),
            /* :: */[
              Emotion.hover(/* :: */[
                    Emotion.transform(/* `scale */[
                          -120664438,
                          1.1
                        ]),
                    /* [] */0
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

export {
  card ,
  img ,
  
}
/* card Not a pure module */
